version: '3.8'
services:
  backend:
    platform: linux/amd64
    build: ./backend
    image: miracle-backend
    container_name: miracle-backend
    ports:
      - "8090:8090"
      - "465:465"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/miracle_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

  db:
    image: postgres:14.5-alpine
    container_name: miracle_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=miracle_service
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

  frontend:
    platform: linux/amd64
    image: miracle-frontend
    container_name: miracle-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run start
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge