drop table IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(50),
    email    varchar(50)                             not null,
    UNIQUE (email),

    constraint USERS_PK
        primary key (id)
);