-- drop table IF EXISTS Users;
-- drop table IF EXISTS Images;
-- drop table IF EXISTS Items;

CREATE TABLE IF NOT EXISTS Users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(50),
    email    varchar(50)                             not null,
    image_id bigint,
    user_role varchar,
    "password" text,
    active boolean,

    UNIQUE (email),
    constraint USERS_PK
        primary key (id)
);

CREATE TABLE IF NOT EXISTS Images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename     varchar(200),
    size         bigint,
    content_type varchar(50),
    bytes        bytea,
    user_id      bigint,

    constraint IMAGES_PK
        primary key (id)
);

CREATE TABLE IF NOT EXISTS Items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       varchar(200),
    description text,
    price       bigint,
    owner_id    integer,
    posted      TIMESTAMP WITHOUT TIME ZONE,
    image_id    bigint,

    constraint ITEMS_PK
        primary key (id)
);

CREATE TABLE IF NOT EXISTS Images_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename     varchar(200),
    size         bigint,
    content_type varchar(50),
    bytes        bytea,
    item_id      bigint,

    constraint IMAGES_ITEMS_PK
        primary key (id)
);